# --- PENGATURAN NAVIGASI HEADER (Menu Laci) ---
header_pages:
  - profil-sekolah.md
  - guru-staf.md
  - kegiatan.md
  - prestasi.md
  - blog.md
  - galeri.md

# PENTING: MENYETEL JUDUL SITUS MENJADI KOSONG
title: " "

# (HAPUS remote_theme dan plugins)
